spring:
  datasource:
    # Put here your user name
    username: vasko
    # Put here your password
    password: vasko
    url: jdbc:mysql://localhost:3306/car_register_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
